[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  publish = ".next"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"