[build]
  command = "next build && next build && next config --no-lambdas && next export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"